vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: /uploads/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/avatar'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'uuid', transliterate: true }
