version: '3'

services:
  database:
    image: mariadb:10.7.3
    container_name: contacts_database
    restart: unless-stopped
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: unh
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
    volumes:
      - database-data:/var/lib/mysql:rw
      - ./var:/var/www/var
    ports:
      - "3307:3306"
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  web:
    image: nginx:alpine
    container_name: contacts_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:delegated
      - ./tools/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    user: '${USER_ID}:${GROUP_ID}'
    container_name: contacts_php
    restart: unless-stopped
    build:
      context: ./tools/docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database

  ## Development Tools
  mailer:
    image: maildev/maildev:2.0.2
    container_name: contacts_maildev
    restart: unless-stopped
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "1080:80"
    labels:
      com.symfony.server.service-prefix: 'MAILER'

  adminer:
    image: adminer:4.8.1
    container_name: contacts_adminer
    restart: unless-stopped
    depends_on:
      - database
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8082:8080"

  node:
    container_name: contacts_node
    restart: unless-stopped
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./tools/docker/node
    command: yarn run watch
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"

volumes:
  database-data:
    driver:
      local
